site_name: HyDAMO Validation documentation
theme:
  name: "material"
  language: en
plugins:
  - search
  - mkdocstrings
nav:
    - Home: index.md
    - Get Started: guides/get_started.md
    - Contribute: guides/contribute.md
    - Code Reference:
        - DataSets: reference/datasets.md
        - HyDAMO: reference/hydamo.md
        - Functions:
            - General Functions: reference/general_functions.md
            - Logic Functions: reference/logic_functions.md
            - Topologic Functions: reference/topologic_functions.md