name: validatietool

channels:
  - conda-forge

dependencies:
  - python>=3.12
  - black
  - geopandas==0.14.3
  - ipykernel
  - jupyter
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - numpy
  - pandas==2.2.0
  - pip
  - pytest
  - pytest-cov
  - pyogrio
  - rasterio==1.3.9
  - rasterstats==0.19.0
  - rtree
  - shapely==2.0.2
  - tqdm
  - twine
