name: validatietool

channels:
  - conda-forge

dependencies:
  - python>=3.12
  - geopandas==0.14.3
  - jupyter
  - numpy
  - pip
  - pandas==2.2.0
  - pyogrio
  - rasterio==1.3.9
  - rasterstats==0.19.0
  - shapely==2.0.2
  - rtree